# Generated by Django 5.0.1 on 2024-01-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Finished', 'Finished')], default='In Progress', max_length=50)),
            ],
        ),
    ]
