# Generated by Django 5.0.1 on 2024-01-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todoapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Finished', 'Finished')], default='In Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
